### ISSUE TITLE
Add description property to Widgets schema

### ISSUE THREAD

**Issue by tonebonekone** [NearSocial/standards#10]
Would like widgets schema to allow for other properties. To begin with, a description would help users navigate widgets. 

```
[widget_name] = {
     sourceCode: string,
     description: string
}
```

**Comment by evgenykuzyakov** [comment]
I need to refresh the standards to reflect Metadata object that is present for the widgets:
```
[widget_name]: {
  "": source,
  "metadata": Metadata,
}
```

See https://near.social/#/mob.near/widget/WidgetSource?src=mob.near/widget/WidgetMetadata
and https://near.social/#/mob.near/widget/WidgetSource?src=mob.near/widget/WidgetMetadataEditor
