### ISSUE TITLE
Profile does not follow LinkTree standard

### ISSUE THREAD

**Issue by volovyks** [NearSocial/standards#9]
Looks like [profile](https://github.com/NearSocial/standards/blob/main/types/profile/Profile.md) is not following [LinkTree](https://github.com/NearSocial/standards/blob/main/types/profile/LinkTree.md) standard. t is using `string` with an acc name instead of an `object` with more detailed info.

**Comment by evgenykuzyakov** [comment]
LinkTree standard is just a key-value. The schema defines the value as a string. The known providers above are what is supported by the Profile

**Comment by evgenykuzyakov** [comment]
Clarified in the #11
